# Generated by Django 3.2.7 on 2021-09-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receita2',
            new_name='Receita',
        ),
        migrations.DeleteModel(
            name='ReceitaMolde',
        ),
    ]
